# Stage 1: Build 
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npx vite build

# Stage 2: Production 
FROM nginx:alpine
# ก๊อปปี้ไฟล์ที่ Build เสร็จแล้วไปไว้ที่โฟลเดอร์มาตรฐานของ Nginx
COPY --from=builder /app/dist /usr/share/nginx/html
# คืนค่าบรรทัดที่ก๊อบปี้ nginx.conf เพื่อให้ใช้ configuration แก้ไขปัญหาการ Refresh 404
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
